#!/bin/bash
# Author: Vu Ngo
# This script calculates some useful QC metrics from BAM files produced by SENTIEON (UMI processed)

SENTIEON='/mnt/clinical/bin/sentieon/sentieon-genomics-202010/bin/sentieon'
GENOME='/mnt/swu/binary/LynchPanelPipeline_142genes/ref/whole_genome.fa' # this genome is assumed to be hg19

sentieon_bam=$1 # bam file generated by sentieon
out_dir=$2
NUMTHREAD=${3:-4} # default number of threads is 4, if not specified

echo "Running with $NUMTHREAD threads..."
mkdir $out_dir




$SENTIEON driver -t $NUMTHREAD -r $GENOME -i $sentieon_bam \
          --algo GCBias --summary $out_dir/GC_SUMMARY.txt $out_dir/GC_METRIC.txt \
          --algo MeanQualityByCycle $out_dir/MQ_METRIC.txt \
          --algo QualDistribution $out_dir/QD_METRIC.txt \
          --algo InsertSizeMetricAlgo $out_dir/IS_METRIC.txt  \
          --algo AlignmentStat $out_dir/ALN_METRIC.txt
          
          
$SENTIEON plot GCBias -o $out_dir/GC_METRIC.pdf $out_dir/GC_METRIC.txt
$SENTIEON plot MeanQualityByCycle -o $out_dir/MQ_METRIC.pdf $out_dir/MQ_METRIC.txt
$SENTIEON plot QualDistribution -o $out_dir/QD_METRIC.pdf $out_dir/QD_METRIC.txt
$SENTIEON plot InsertSizeMetricAlgo -o $out_dir/IS_METRIC.pdf $out_dir/IS_METRIC.txt